# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: olivetti-deployment
  labels:
    app: olivetti-flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: olivetti-flask
  template:
    metadata:
      labels:
        app: olivetti-flask
    spec:
      containers:
      - name: olivetti-flask
        image: mathursahab8897/olivetti-flask:latest
        imagePullPolicy: Never 
        ports:
        - containerPort: 5000